# Generated by Django 5.2.7 on 2025-10-08 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('rides', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='location_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_end', to='locations.location'),
        ),
        migrations.AddField(
            model_name='ride',
            name='location_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_start', to='locations.location'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
