# Generated by Django 5.2.7 on 2026-04-20 00:00

import django.db.models.deletion
from django.db import migrations, models


def _create_ride_listing_notify_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION rides_notify_ride_listing_change()
        RETURNS trigger AS $$
        DECLARE
            ride_listing_ride_id bigint;
        BEGIN
            ride_listing_ride_id := COALESCE(NEW.ride_id, OLD.ride_id);
            PERFORM pg_notify(
                'ride_listing_events',
                json_build_object(
                    'event_type',
                    'ride_listing_changed',
                    'ride_id',
                    ride_listing_ride_id
                )::text
            );
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER rides_ride_listing_record_notify_change
        AFTER INSERT OR UPDATE OR DELETE ON rides_ridelistingrecord
        FOR EACH ROW
        EXECUTE FUNCTION rides_notify_ride_listing_change();
        """
    )


def _drop_ride_listing_notify_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP TRIGGER IF EXISTS rides_ride_listing_record_notify_change ON rides_ridelistingrecord")
    schema_editor.execute("DROP FUNCTION IF EXISTS rides_notify_ride_listing_change()")


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideListingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("available_seats", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_methods", models.JSONField(blank=True, default=list)),
                ("departure_time", models.TimeField()),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("route_stops", models.JSONField(blank=True, default=list)),
                ("driver_name", models.CharField(max_length=150)),
                ("driver_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("driver_total_rides", models.PositiveIntegerField(default=0)),
                ("driver_avatar", models.CharField(blank=True, max_length=500)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("restrictions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_record",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_date", "departure_time", "id"],
            },
        ),
        migrations.RunPython(
            _create_ride_listing_notify_trigger,
            _drop_ride_listing_notify_trigger,
        ),
    ]
