# Generated by Django 5.2.7 on 2025-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(default='Brasília', max_length=100)),
                ('street', models.CharField(default='Brasília', max_length=100)),
                ('number', models.CharField(default='Brasília', max_length=10)),
                ('complement', models.CharField(default='Brasília', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Brasília', max_length=50)),
                ('state', models.CharField(default='DF', max_length=2)),
                ('reference', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
